server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:

        - id: patient-service
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/api/patients/**

        - id: doctor-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/api/doctors/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: 1.0   # 100% (dev). In prod use 0.1 or less.
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"
